version: '3.8'

services:
  web:
    image: luisleandro9673/odoo-18-comunity-afip:latest
    container_name: odoo18_app
    depends_on:
      - db
    ports:
      - "8071:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons:ro
      - odoo-data:/var/lib/odoo
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    restart: always

  db:
    image: postgres:13
    container_name: odoo18_db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
  odoo-data:
